version: '3.9'

services:
  redis:
    image: redis
    container_name: redis
    command: redis-server --requirepass 1
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: '1'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: '1'
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db

volumes:
  redis-data:
  mysql-data:
  mongodb-data:
